project_id = "jsmsyezkfxtgmxvgfuxx"

[functions.invite-user]
verify_jwt = true

[functions.request-password-reset]
verify_jwt = false
[functions.snap-upload]
verify_jwt = false

[functions.public-quote-accept]
verify_jwt = false

[functions.public-brand-logo]
verify_jwt = false

[functions.manage-user]
verify_jwt = true

[functions.data-import]
verify_jwt = false
